"""
Build command - builds for production.

Builds the project for production deployment.
"""

from typing import Any

from teloce.project.discovery import ProjectDiscovery
from teloce.project.configuration import ProjectConfiguration
from teloce.build.builder import Builder


def build_command(args: Any) -> int:
    """
    Build for production.
    
    Args:
        args: Command-line arguments.
        
    Returns:
        Exit code.
    """
    print("📦 Teloce Build")
    print("=" * 40)
    
    # Discover project
    discovery = ProjectDiscovery()
    discovery.discover()
    
    print(f"📁 Project: {discovery.get_project_name()}")
    
    # Load configuration
    config = ProjectConfiguration()
    config.load(discovery.config_file)
    
    # Get build config
    build_config = config.get_build_config()
    out_dir = args.out_dir if args.out_dir is not None else build_config.get('out_dir', 'dist')
    minify = args.minify or (not args.no_minify and build_config.get('minify', False))
    compiler_config = config.get_compiler_config()
    source_map = args.source_map or compiler_config.get('source_maps', build_config.get('source_maps', False))
    clean = not getattr(args, 'no_clean', False) and build_config.get('clean', True)
    
    print(f"📂 Output: {out_dir}")
    print(f"⚡ Minify: {'Yes' if minify else 'No'}")
    print(f"🗺️  Source Maps: {'Yes' if source_map else 'No'}")
    print()
    
    # Build
    static_mode = bool(getattr(args, 'static', False) or build_config.get('static', False))
    builder = Builder({
        'mode': 'production',
        'production': True,
        'minify': minify,
        'source_maps': source_map,
        'dev': False,
        'clean': clean,
        'static_dir': build_config.get('static_dir', 'static'),
        'hash_assets': (not getattr(args, 'no_hash_assets', False)
                        and (getattr(args, 'hash_assets', False)
                             or build_config.get('hash_assets', True))),
        'extract_css': not getattr(args, 'no_extract_css', False) and build_config.get('extract_css', True),
        'bundle': getattr(args, 'bundle', False) or build_config.get('bundle', False),
        'bundler': getattr(args, 'bundler', None) or build_config.get('bundler', 'teloce'),
        'code_splitting': not getattr(args, 'no_splitting', False),
        'bundle_entry': getattr(args, 'entry', None),
        'report': getattr(args, 'report', None) or build_config.get('report'),
        'max_asset_size': getattr(args, 'max_size', 0) or build_config.get('max_asset_size', 0),
        'ssr': getattr(args, 'ssr', False) or build_config.get('ssr', False) or static_mode,
        'static': static_mode,
        'shared_runtime': build_config.get('shared_runtime', True),
        'lazy_components': ([item.strip() for item in args.lazy_components.split(',') if item.strip()]
                            if getattr(args, 'lazy_components', None) is not None
                            else build_config.get('lazy_components', [])),
        'tree_shake': not getattr(args, 'no_tree_shake', False) and build_config.get('tree_shake', True),
    })
    
    result = builder.build(discovery.root_dir, out_dir)
    
    # Print results
    print("✅ Build complete!")
    print()
    print("📊 Statistics:")
    print(f"   Total files: {result['total']}")
    print(f"   Compiled: {result['compiled']}")
    print(f"   Failed: {result['failed']}")
    print(f"   Assets copied: {result.get('assets_copied', 0)}")
    print(f"   Generated bytes: {result.get('total_bytes', 0)}")
    if result.get('report'):
        print(f"   Report: {result['report']}")
    for warning in result.get('size_warnings', []):
        print(f"   ⚠️  {warning['output']}: {warning['message']}")
    print(f"   Duration: {result['duration']:.2f}s")
    
    if result['errors']:
        print()
        print("❌ Errors:")
        for error in result['errors']:
            print(f"   {error['file']}: {error['error']}")
        return 1
    
    return 0
