"""
JavaScript code generator.

Generates complete JavaScript code from component AST.
"""

from typing import List, Optional, Dict, Any
from teloce.ast.nodes import (
    ASTNode, ElementNode, TextNode, InterpolationNode,
    ForNode, IfNode,
    ComponentNode, SlotNode, FragmentNode
)
from teloce.sfc.component import Component
from teloce.javascript.module import ModuleGenerator
from teloce.javascript.imports import ImportGenerator
from teloce.javascript.exports import ExportGenerator
from teloce.javascript.dom import DOMGenerator
from teloce.javascript.helpers import HelperGenerator


class JavaScriptGenerator:
    """
    Generates JavaScript code from a component AST.
    """
    
    def __init__(self, options: Optional[Dict[str, Any]] = None):
        self.options = options or {}
        self.dev = self.options.get('dev', True)
        self.minify = self.options.get('minify', False)
        self.target = self.options.get('target', 'es2020')
        self.indent_level = 0
        
        self.module_gen = ModuleGenerator(options)
        self.import_gen = ImportGenerator(options)
        self.export_gen = ExportGenerator(options)
        self.dom_gen = DOMGenerator(options)
        self.helper_gen = HelperGenerator(options)
    
    def generate(self, ast: List[ASTNode], component: Component) -> str:
        """
        Generate JavaScript code from the AST and component data.
        
        Args:
            ast: The template AST
            component: The component data
            
        Returns:
            Generated JavaScript code.
        """
        self.indent_level = 0
        lines = []
        
        # Add header
        lines.append('// Generated by Teloce-Py')
        lines.append('')
        
        # Generate runtime imports if requested. The default output is
        # standalone and does not require npm or a package named `teloce`.
        runtime_imports = self._generate_runtime_imports()
        if runtime_imports:
            lines.append(runtime_imports)
            lines.append('')
        
        # Generate component code
        component_code = self._generate_component(ast, component)
        lines.append(component_code)
        
        # Add mount code if specified
        if self.options.get('mount', True):
            lines.append('')
            lines.append(self._generate_mount_code(component))
        
        return '\n'.join(lines)
    
    def _generate_component(self, ast: List[ASTNode], component: Component) -> str:
        """Generate the component definition."""
        lines = []
        identifier = self._component_identifier(component.name)
        lines.append(f'const {identifier} = {{')
        self.indent_level += 1
        
        # Component name
        lines.append(f'{self._indent()}name: "{component.name}",')
        lines.append('')
        
        # Data function
        if component.script.data:
            lines.append(f'{self._indent()}data() {{')
            self.indent_level += 1
            data_body = getattr(component.script, "data_body", None)
            if data_body:
                for line in data_body.split('\n'):
                    if line.strip():
                        lines.append(f'{self._indent()}{line}')
            else:
                lines.append(f'{self._indent()}return {component.script.data};')
            self.indent_level -= 1
            lines.append(f'{self._indent()}}},')
            lines.append('')
        
        # Props
        if component.script.props:
            lines.append(f'{self._indent()}props: {self._generate_props(component.script.props)},')
            lines.append('')
        
        # Computed
        if component.script.computed:
            lines.append(f'{self._indent()}computed: {{')
            self.indent_level += 1
            for name, body in component.script.computed.items():
                lines.append(f'{self._indent()}{name}() {{')
                self.indent_level += 1
                for line in body.split('\n'):
                    if line.strip():
                        lines.append(f'{self._indent()}{line}')
                self.indent_level -= 1
                lines.append(f'{self._indent()}}},')
            self.indent_level -= 1
            lines.append(f'{self._indent()}}},')
            lines.append('')
        
        # Methods
        if component.script.methods:
            lines.append(f'{self._indent()}methods: {{')
            self.indent_level += 1
            for name, body in component.script.methods.items():
                params = getattr(component.script, "method_params", {}).get(name, "")
                prefix = "async " if getattr(component.script, "method_async", {}).get(name, False) else ""
                lines.append(f'{self._indent()}{prefix}{name}({params}) {{')
                self.indent_level += 1
                for line in body.split('\n'):
                    if line.strip():
                        lines.append(f'{self._indent()}{line}')
                self.indent_level -= 1
                lines.append(f'{self._indent()}}},')
            self.indent_level -= 1
            lines.append(f'{self._indent()}}},')
            lines.append('')
        
        # Lifecycle hooks
        if component.script.lifecycle:
            for hook, body in component.script.lifecycle.items():
                params = getattr(component.script, "lifecycle_params", {}).get(hook, "")
                prefix = "async " if getattr(component.script, "lifecycle_async", {}).get(hook, False) else ""
                lines.append(f'{self._indent()}{prefix}{hook}({params}) {{')
                self.indent_level += 1
                for line in body.split('\n'):
                    if line.strip():
                        lines.append(f'{self._indent()}{line}')
                self.indent_level -= 1
                lines.append(f'{self._indent()}}},')
            lines.append('')
        
        # Template render function
        lines.append(f'{self._indent()}render(ctx) {{')
        self.indent_level += 1
        lines.append(f'{self._indent()}const root = {self._generate_template(ast)};')
        lines.append(f'{self._indent()}return root;')
        self.indent_level -= 1
        lines.append(f'{self._indent()}}}')
        
        self.indent_level -= 1
        lines.append('};')
        
        return '\n'.join(lines)
    
    def _generate_template(self, ast: List[ASTNode]) -> str:
        """Generate the template render function body."""
        if len(ast) == 0:
            return "document.createDocumentFragment()"
        
        if len(ast) == 1:
            return self._generate_node(ast[0])
        
        # Multiple root nodes - use fragment
        return self.dom_gen.generate_fragment(FragmentNode(ast))
    
    def _generate_node(self, node: ASTNode) -> str:
        """Generate code for a single AST node."""
        if isinstance(node, ElementNode):
            return self.dom_gen.generate_element(node)
        elif isinstance(node, TextNode):
            return self.dom_gen.generate_text(node)
        elif isinstance(node, InterpolationNode):
            return self.dom_gen.generate_interpolation(node)
        elif isinstance(node, ForNode):
            return self.dom_gen.generate_for(node)
        elif isinstance(node, IfNode):
            return self.dom_gen.generate_if(node)
        elif isinstance(node, ComponentNode):
            return self.dom_gen.generate_component(node)
        elif isinstance(node, SlotNode):
            return self.dom_gen.generate_slot(node)
        elif isinstance(node, FragmentNode):
            return self.dom_gen.generate_fragment(node)
        else:
            return "document.createTextNode('')"
    
    def _generate_props(self, props: Dict[str, Any]) -> str:
        """Generate props definition."""
        if not props:
            return "{}"
        
        prop_strings = []
        for name, prop_def in props.items():
            if isinstance(prop_def, dict):
                parts = []
                if prop_def.get('type'):
                    parts.append(f"type: {prop_def['type']}")
                if prop_def.get('required'):
                    parts.append("required: true")
                if prop_def.get('default') is not None:
                    default = prop_def['default']
                    if isinstance(default, str):
                        parts.append(f"default: '{default}'")
                    else:
                        parts.append(f"default: {default}")
                if prop_def.get('validator'):
                    parts.append(f"validator: {prop_def['validator']}")
                
                if parts:
                    prop_strings.append(f"{name}: {{{', '.join(parts)}}}")
                else:
                    prop_strings.append(name)
            else:
                prop_strings.append(name)
        
        return f"{{{', '.join(prop_strings)}}}"
    
    def _generate_mount_code(self, component: Component) -> str:
        """Generate mount code."""
        return f"""
// Mount the component without an external runtime.
export function mount(target = '#app', props = {{}}) {{
  if (typeof target === 'string') target = document.querySelector(target);
  if (!target) throw new Error('Teloce mount target was not found');
  const state = {{ ...({self._component_identifier(component.name)}.data ? {self._component_identifier(component.name)}.data() : {{}}), ...props }};
  const root = {self._component_identifier(component.name)}.render(state);
  target.replaceChildren(root);
  return {{ target, state, component: {self._component_identifier(component.name)} }};
}}
"""
    
    def _generate_runtime_imports(self) -> str:
        """Generate runtime imports."""
        module = self.options.get('runtime_module')
        return f"import {{ createApp }} from {module!r};" if module else ""

    @staticmethod
    def _component_identifier(name: str) -> str:
        """Return a valid JavaScript identifier for a component name."""
        import re
        identifier = re.sub(r'\W+', '_', name or 'Component')
        if not identifier or identifier[0].isdigit():
            identifier = '_' + identifier
        return identifier
    
    def _indent(self) -> str:
        """Get the current indentation."""
        return '  ' * self.indent_level
